/**
 * `client/rest.ts` — the typed REST transport (API.md §10, §10.1).
 *
 * Everything here is **schema driven**: the route table is `wire/rest/*` reached through the
 * GENERATED barrel `wire/rest/index.ts`. Adding a route to the terminal therefore never touches this
 * file — a new `Rest.<Group>.<Route>` entry appears in the barrel and is immediately callable as
 * `rest.request('<Group>.<Route>', …)` and as `client.<group>.<route>(…)`.
 *
 * What a request does, in order:
 *   1. look the route up by id (`'Auth.Login'`) or by `(method, path)`;
 *   2. validate `params` / `query` / `body` locally with the route's zod schemas (a failure is a
 *      client-side `TerminalApiError { code:'VALIDATION_FAILED', details.location }` — no request
 *      leaves the process);
 *   3. build `baseUrl + '/api/v1' + path` with `:param` substitution and a `URLSearchParams` query;
 *   4. send `x-trace-id` (one per user action, OPS-07), `x-client-version`, and either
 *      `Authorization: Bearer …` (bearer mode) or `x-requested-with: terminal` on mutations plus
 *      `credentials:'include'` (cookie mode, API.md §1.3 L129 / §0 L59);
 *   5. honour `If-None-Match` for the ETag routes (`/universe/snapshot`, `/functions`, `/fields`;
 *      API.md L447, L493, L563) and answer a `304` from the in-memory cache;
 *   6. parse the body with the route's response schema, throwing `VALIDATION_FAILED` on drift;
 *   7. map the §2 error envelope to a typed `TerminalApiError`;
 *   8. surface `x-quota-*`, `x-deprecated-fields` through `onTrace` and `x-server-version` /
 *      `x-min-client-version` / `x-dictionary-version` through `onVersion` (§11).
 */
import type { z } from 'zod';

import { ErrorEnvelope, RETRYABLE_ERROR_CODES, type ErrorCode } from '../wire/envelope.js';
import {
  createFieldsApi,
  type FieldDictionary,
  type FieldFormatter,
  type FieldsApi,
} from '../fields/index.js';
import { registry, type FunctionRegistry } from '../functions/index.js';
import { LiveClient } from './ws.js';
// The barrel is GENERATED by `scripts/gen-function-index.ts` from `sdk/src/wire/rest/*.ts`
// (WORKPLAN §1.10). It is never hand-written — including by this file.
import * as RestBarrel from '../wire/rest/index.js';

// ---------------------------------------------------------------------------
// The route-table contract this transport reads
// ---------------------------------------------------------------------------

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD';

/**
 * The shape every `wire/rest/<group>.ts` entry must have. Only `method` and `path` are required —
 * they are also what identifies an entry as a route rather than a plain zod schema exported from the
 * same module.
 */
export interface RouteDef {
  readonly method: HttpMethod;
  readonly path: string;
  readonly params?: z.ZodType;
  readonly query?: z.ZodType;
  readonly body?: z.ZodType;
  readonly response?: z.ZodType;
  /** Force (`true`) or forbid (`false`) the conditional-request cache; defaults to the §5 table. */
  readonly etag?: boolean;
  /** Non-JSON responses (the §9 CSV exports) — the value is sent as `accept`. */
  readonly accept?: string;
}

type RouteLike = { readonly method: string; readonly path: string };

/** The barrel exports either a `Rest` object of groups, or the groups themselves. Both work. */
type Barrel = typeof RestBarrel;
export type RestRegistry = Barrel extends { Rest: infer R } ? R : Barrel;

type Get<D, K extends PropertyKey> = K extends keyof D ? D[K] : undefined;
type Get2<D, G extends PropertyKey, K extends PropertyKey> = G extends keyof D
  ? K extends keyof D[G]
    ? D[G][K]
    : never
  : never;
type InputOf<S> = S extends z.ZodType ? z.input<S> : never;
type OutputOf<S> = S extends z.ZodType ? z.output<S> : never;
type Part<D, K extends string> = [InputOf<Get<D, K>>] extends [never]
  ? object
  : Record<K, InputOf<Get<D, K>>>;

/** `{ params?, query?, body? }`, each typed by the route's zod schema (API.md L1291). */
export type RouteArgs<D> = Part<D, 'params'> & Part<D, 'query'> & Part<D, 'body'>;

/** The route's decoded response, or `undefined` for the `204`s that declare no schema. */
export type RouteResponseOf<D> = [OutputOf<Get<D, 'response'>>] extends [never]
  ? undefined
  : OutputOf<Get<D, 'response'>>;

type Keys<T> = Extract<keyof T, string>;
/** Plain object literals (the group objects) have an implicit index signature; zod schemas — being
 * class instances — do not, which is what keeps the third level of the walk below off `z.ZodType`. */
type Nested<T> = T extends Record<string, unknown> ? T : never;
type UnionToIntersection<U> = (U extends unknown ? (x: U) => void : never) extends (
  x: infer I,
) => void
  ? I
  : never;

/**
 * Every `{ '<id>': def }` singleton the barrel yields, at any of the three nesting depths the
 * runtime `buildIndex()` accepts:
 *   1. `export const Rest = { Auth: { Login: {…} } }`       → 'Auth.Login'
 *   2. `export const Auth = { Login: {…} }` (re-exported)   → 'Auth.Login'
 *   3. `export * as auth from './auth.js'` — a namespace that *contains* `Auth` → 'Auth.Login'
 * Depth 3 names the route after the group object it found, not after the module namespace, so the
 * ids the type layer produces are exactly the ids `buildIndex()` registers.
 */
type RouteSingletons<R> = {
  [G in Keys<R>]: R[G] extends RouteLike
    ? Record<G, R[G]>
    : {
        [K in Keys<R[G]>]: R[G][K] extends RouteLike
          ? Record<`${G}.${K}`, R[G][K]>
          : {
              [S in Keys<Nested<R[G][K]>>]: Nested<R[G][K]>[S] extends RouteLike
                ? Record<`${K}.${S}`, Nested<R[G][K]>[S]>
                : never;
            }[Keys<Nested<R[G][K]>>];
      }[Keys<R[G]>];
}[Keys<R>];

/** Route id → route definition, for every route the barrel declares. */
export type RouteMap = UnionToIntersection<RouteSingletons<RestRegistry>>;

/** `'Auth.Login' | 'Data.Request' | 'Functions.Run' | …` — every route in the barrel. */
export type RouteId = Keys<RouteMap>;

/** The definition behind a `RouteId`. */
export type RouteDefOf<Id extends string> = Id extends keyof RouteMap
  ? RouteMap[Id]
  : Id extends keyof RestRegistry
    ? RestRegistry[Id]
    : Id extends `${infer G}.${infer K}`
      ? Get2<RestRegistry, G, K>
      : never;

/** The routes of one group, keyed by their short names — `GroupOf<'Auth'>['Login']`. */
export type GroupOf<G extends string> = {
  [Id in RouteId as Id extends `${G}.${infer K}` ? K : never]: RouteMap[Id];
};

export type RouteResponse<Id extends string> = RouteResponseOf<RouteDefOf<Id>>;

// ---------------------------------------------------------------------------
// Options and callbacks
// ---------------------------------------------------------------------------

/** OPS-07 — one trace event per REST call, whatever the outcome. */
export interface TraceEvent {
  traceId: string;
  route: string;
  ms: number;
  status: number;
  /** `x-quota-*` (API.md L1160) when the response carried them. */
  quota?: Readonly<Record<string, { used: number; limit: number }>> | undefined;
  /** `x-deprecated-fields` (API.md L1137) split on commas. */
  deprecatedFields?: readonly string[] | undefined;
  /** true when the answer came from the ETag cache (HTTP 304). */
  cached?: boolean | undefined;
  /** the error code, when the call failed. */
  errorCode?: ErrorCode | undefined;
}

/** §11 — version headers, surfaced whenever they change. */
export interface VersionEvent {
  serverVersion: string;
  minClientVersion: string;
  dictionaryVersion: string;
}

/** API.md §10 L1229-1238, plus the WP-01 injection points marked below. */
export interface ClientOptions {
  /** `'https://host'` — REST at `baseUrl + '/api/v1'`, WS at `ws(s)://host/ws/v1`. */
  baseUrl: string;
  /** bearer API key; omitted for cookie sessions (browser). */
  token?: string | undefined;
  /** `'web/0.1.0'` | `'sdk-js/0.1.0'` → `x-client-version`, `hello.client`. */
  clientVersion: string;
  fetch?: typeof fetch | undefined;
  WebSocket?: typeof WebSocket | undefined;
  /** default `crypto.randomUUID()`; one per user action (OPS-07). */
  traceId?: (() => string) | undefined;
  onTrace?: ((e: TraceEvent) => void) | undefined;
  onVersion?: ((e: VersionEvent) => void) | undefined;
  /** default 250 (consumed by `LiveClient`, WP-13). */
  conflationMs?: number | undefined;

  // ── WP-01 additions (not in API.md §10; all optional, all with working defaults) ──
  /** cookie mode only; default `'include'`. Ignored when `token` is set. */
  credentials?: RequestCredentials | undefined;
  /** conditional-request cache for the ETag routes; default `true`. */
  cacheEtags?: boolean | undefined;
  /** headers merged into every request (below per-call headers). */
  headers?: Readonly<Record<string, string>> | undefined;
  /** the generated `fields/fields.json`, when the host wants a dictionary before the first fetch. */
  fieldsSeed?: FieldDictionary | undefined;
  /** override for `core/fields/format.ts` (tests); the core formatter is used otherwise. */
  format?: FieldFormatter | undefined;
}

/** Untyped call arguments — what `RestClient.call()` takes. */
export interface AnyRouteArgs {
  params?: unknown;
  query?: unknown;
  body?: unknown;
}

export interface RequestOptions {
  /** overrides the per-client `traceId()` factory for this call (one id per user action). */
  traceId?: string | undefined;
  signal?: AbortSignal | undefined;
  headers?: Readonly<Record<string, string>> | undefined;
  accept?: string | undefined;
  /** skip response-schema validation (streaming/large payloads in tests). */
  skipResponseValidation?: boolean | undefined;
  /**
   * Called with every response header (lower-cased) before the body is decoded — how a caller gets
   * `content-disposition`, `x-as-of-valid`, `x-provenance` and `etag` off a CSV export (API.md §9).
   */
  onResponseHeaders?: ((headers: Record<string, string>) => void) | undefined;
}

// ---------------------------------------------------------------------------
// TerminalApiError — API.md §2 → §10.1 L1296-1298
// ---------------------------------------------------------------------------

export interface TerminalApiErrorInit {
  code: ErrorCode;
  message: string;
  status: number;
  traceId: string;
  retryable?: boolean | undefined;
  retryAfterMs?: number | undefined;
  details?: Record<string, unknown> | undefined;
  route?: string | undefined;
  cause?: unknown;
}

export class TerminalApiError extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  readonly traceId: string;
  readonly retryable: boolean;
  readonly retryAfterMs?: number | undefined;
  readonly details?: Record<string, unknown> | undefined;
  /** the `RouteId` the call was made against — WP-01 addition, for panel footers and logs. */
  readonly route?: string | undefined;

  constructor(init: TerminalApiErrorInit) {
    super(init.message, init.cause !== undefined ? { cause: init.cause } : undefined);
    this.name = 'TerminalApiError';
    this.code = init.code;
    this.status = init.status;
    this.traceId = init.traceId;
    this.retryable = init.retryable ?? RETRYABLE_ERROR_CODES.includes(init.code);
    this.retryAfterMs = init.retryAfterMs;
    this.details = init.details;
    this.route = init.route;
  }
}

// ---------------------------------------------------------------------------
// The route index — built once from the generated barrel
// ---------------------------------------------------------------------------

/** A zod schema seen structurally, so the transport never depends on a zod version. */
interface Schema {
  safeParse(data: unknown): { success: boolean; data?: unknown; error?: { issues?: unknown } };
}

interface IndexedRoute {
  readonly id: string;
  readonly group: string | null;
  readonly name: string;
  readonly method: HttpMethod;
  /** normalised (`:code` → `{}`) — the lookup key. */
  readonly path: string;
  /** exactly as `wire/rest` spelled it, `:code` markers intact — what the URL is built from. */
  readonly spelling: string;
  readonly params: Schema | null;
  readonly query: Schema | null;
  readonly body: Schema | null;
  readonly response: Schema | null;
  readonly etag: boolean;
  readonly accept: string | null;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null;
}

function isSchema(v: unknown): v is Schema {
  return isRecord(v) && typeof (v as { safeParse?: unknown }).safeParse === 'function';
}

function isRouteLike(v: unknown): v is RouteDef {
  return (
    isRecord(v) &&
    typeof (v as { method?: unknown }).method === 'string' &&
    typeof (v as { path?: unknown }).path === 'string'
  );
}

/** `/functions/:code/run` and `/functions/{code}/run` index to the same key. */
function normalisePath(path: string): string {
  const withSlash = path.startsWith('/') ? path : `/${path}`;
  const stripped = withSlash.replace(/:[A-Za-z0-9_]+/g, '{}').replace(/\{[A-Za-z0-9_]+\}/g, '{}');
  return stripped.length > 1 && stripped.endsWith('/') ? stripped.slice(0, -1) : stripped;
}

/** API.md L447, L493, L563 — the three routes that answer `304`. */
const DEFAULT_ETAG_PATHS = new Set(['/universe/snapshot', '/functions', '/fields']);

const SAFE_METHODS = new Set<HttpMethod>(['GET', 'HEAD']);

function pick(def: RouteDef, ...keys: readonly string[]): Schema | null {
  const bag = def as unknown as Record<string, unknown>;
  for (const key of keys) {
    const value = bag[key];
    if (isSchema(value)) return value;
  }
  return null;
}

function trimPath(path: string): string {
  const withSlash = path.startsWith('/') ? path : `/${path}`;
  return withSlash.length > 1 && withSlash.endsWith('/') ? withSlash.slice(0, -1) : withSlash;
}

function toIndexedRoute(id: string, def: RouteDef): IndexedRoute {
  const dot = id.lastIndexOf('.');
  const method = def.method.toUpperCase() as HttpMethod;
  const path = normalisePath(def.path);
  const bag = def as unknown as Record<string, unknown>;
  const accept = typeof bag.accept === 'string' ? bag.accept : null;
  const etag =
    typeof def.etag === 'boolean'
      ? def.etag
      : SAFE_METHODS.has(method) && DEFAULT_ETAG_PATHS.has(path);
  return {
    id,
    group: dot > 0 ? id.slice(0, dot) : null,
    name: dot > 0 ? id.slice(dot + 1) : id,
    method,
    path,
    spelling: trimPath(def.path),
    params: pick(def, 'params', 'path'),
    query: pick(def, 'query', 'search'),
    body: pick(def, 'body', 'request', 'input'),
    response: pick(def, 'response', 'result', 'output'),
    etag,
    accept,
  };
}

let routeIndex: Map<string, IndexedRoute> | null = null;
let pathIndex: Map<string, string> | null = null;
let groupIndex: Map<string, IndexedRoute[]> | null = null;

function barrelRegistry(): Record<string, unknown> {
  const barrel = RestBarrel as unknown as Record<string, unknown>;
  const rest = barrel.Rest;
  return isRecord(rest) ? rest : barrel;
}

function buildIndex(): Map<string, IndexedRoute> {
  const routes = new Map<string, IndexedRoute>();
  const paths = new Map<string, string>();
  const groups = new Map<string, IndexedRoute[]>();
  const add = (id: string, def: RouteDef): void => {
    const route = toIndexedRoute(id, def);
    routes.set(id, route);
    const pathKey = `${route.method} ${route.path}`;
    if (!paths.has(pathKey)) paths.set(pathKey, id);
    if (route.group !== null) {
      const bucket = groups.get(route.group);
      if (bucket) bucket.push(route);
      else groups.set(route.group, [route]);
    }
  };
  // Three shapes are accepted, so the generated barrel can be written any of the usual ways:
  //   1. `export const Rest = { Auth: { Login: {...} } }`      → 'Auth.Login'
  //   2. `export * from './auth.js'` (the group object `Auth`) → 'Auth.Login'
  //   3. `export * as auth from './auth.js'` (a namespace that *contains* `Auth`) → 'Auth.Login'
  for (const [key, value] of Object.entries(barrelRegistry())) {
    if (isRouteLike(value)) {
      add(key, value);
      continue;
    }
    if (!isRecord(value)) continue;
    for (const [name, def] of Object.entries(value)) {
      if (isRouteLike(def)) {
        add(`${key}.${name}`, def);
        continue;
      }
      if (!isRecord(def)) continue;
      // A module namespace: the group object one level down names the group.
      for (const [subName, subDef] of Object.entries(def)) {
        if (isRouteLike(subDef) && !routes.has(`${name}.${subName}`)) {
          add(`${name}.${subName}`, subDef);
        }
      }
    }
  }
  routeIndex = routes;
  pathIndex = paths;
  groupIndex = groups;
  return routes;
}

function routes(): Map<string, IndexedRoute> {
  return routeIndex ?? buildIndex();
}

function paths(): Map<string, string> {
  if (pathIndex === null) buildIndex();
  return pathIndex!;
}

function groups(): Map<string, IndexedRoute[]> {
  if (groupIndex === null) buildIndex();
  return groupIndex!;
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function uncapitalise(s: string): string {
  return s.length === 0 ? s : `${s[0]!.toLowerCase()}${s.slice(1)}`;
}

function now(): number {
  return typeof performance !== 'undefined' && typeof performance.now === 'function'
    ? performance.now()
    : Date.now();
}

function defaultTraceId(): string {
  const webCrypto = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (typeof webCrypto?.randomUUID === 'function') return webCrypto.randomUUID();
  // Platforms without WebCrypto (old Node in a test harness) still need a syntactically valid uuid.
  const hex = '0123456789abcdef';
  let out = '';
  for (let i = 0; i < 36; i += 1) {
    if (i === 8 || i === 13 || i === 18 || i === 23) out += '-';
    else if (i === 14) out += '4';
    else if (i === 19) out += hex[8 + Math.floor(Math.random() * 4)]!;
    else out += hex[Math.floor(Math.random() * 16)]!;
  }
  return out;
}

function scalar(value: unknown): string {
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object' && value !== null) return JSON.stringify(value);
  return String(value);
}

function issuesOf(error: { issues?: unknown } | undefined): unknown[] {
  const issues = error?.issues;
  return Array.isArray(issues) ? issues : [];
}

const STATUS_CODE: Readonly<Record<number, ErrorCode>> = {
  400: 'BAD_REQUEST',
  401: 'AUTH_REQUIRED',
  403: 'FORBIDDEN',
  404: 'NOT_FOUND',
  409: 'DUPLICATE_NAME',
  422: 'BAD_REQUEST',
  426: 'PROTOCOL_VERSION',
  429: 'RATE_LIMITED',
  500: 'INTERNAL',
  503: 'PROVIDER_UNAVAILABLE',
};

function codeForStatus(status: number): ErrorCode {
  return STATUS_CODE[status] ?? (status >= 500 ? 'INTERNAL' : 'BAD_REQUEST');
}

/** `x-quota-daily-instruments: 41/500` → `{ used: 41, limit: 500 }` (API.md L1160). */
function parseQuota(headers: Headers): Record<string, { used: number; limit: number }> | undefined {
  let found: Record<string, { used: number; limit: number }> | undefined;
  headers.forEach((value, key) => {
    if (!key.toLowerCase().startsWith('x-quota-')) return;
    const [used, limit] = value.split('/');
    const u = Number(used);
    const l = Number(limit);
    if (!Number.isFinite(u) || !Number.isFinite(l)) return;
    found ??= {};
    found[key.toLowerCase().slice('x-quota-'.length)] = { used: u, limit: l };
  });
  return found;
}

function isRawBody(value: unknown): boolean {
  if (value === undefined || value === null) return false;
  if (typeof value === 'string') return true;
  if (typeof Blob !== 'undefined' && value instanceof Blob) return true;
  if (typeof FormData !== 'undefined' && value instanceof FormData) return true;
  if (typeof URLSearchParams !== 'undefined' && value instanceof URLSearchParams) return true;
  if (value instanceof ArrayBuffer) return true;
  return ArrayBuffer.isView(value);
}

function headersOf(res: Response): Record<string, string> {
  const out: Record<string, string> = {};
  res.headers.forEach((value, key) => {
    out[key.toLowerCase()] = value;
  });
  return out;
}

/** A non-JSON response (the §9 CSV exports) from a route that declares no response schema. */
export interface TextResponse {
  text: string;
  headers: Record<string, string>;
}

// ---------------------------------------------------------------------------
// RestClient
// ---------------------------------------------------------------------------

interface CacheEntry {
  etag: string;
  value: unknown;
}

export class RestClient {
  readonly options: Readonly<ClientOptions>;
  readonly baseUrl: string;

  #fetch: typeof fetch;
  #cache = new Map<string, CacheEntry>();
  #version: VersionEvent | null = null;

  constructor(opts: ClientOptions) {
    if (typeof opts.baseUrl !== 'string' || opts.baseUrl.length === 0) {
      throw new TypeError('ClientOptions.baseUrl is required');
    }
    if (typeof opts.clientVersion !== 'string' || opts.clientVersion.length === 0) {
      throw new TypeError("ClientOptions.clientVersion is required (e.g. 'sdk-js/0.1.0')");
    }
    this.options = { ...opts };
    this.baseUrl = `${opts.baseUrl.replace(/\/+$/, '')}/api/v1`;
    const injected = opts.fetch ?? globalThis.fetch;
    if (typeof injected !== 'function') {
      throw new TypeError('No fetch implementation: pass ClientOptions.fetch');
    }
    this.#fetch = injected.bind(globalThis);
  }

  /** Every route id the generated barrel declares, sorted. */
  get routeIds(): readonly string[] {
    return [...routes().keys()].sort();
  }

  has(routeId: string): boolean {
    return routes().has(routeId);
  }

  /** The route id for a `(method, path)` pair; `:code` and `{code}` both match. */
  routeIdFor(method: HttpMethod, path: string): string | undefined {
    return paths().get(`${method.toUpperCase()} ${normalisePath(path)}`);
  }

  /** The group names the barrel declares (`'Auth'`, `'Reference'`, …). */
  get groupNames(): readonly string[] {
    return [...groups().keys()].sort();
  }

  /** The route ids in one group. */
  groupRouteIds(group: string): readonly string[] {
    return (groups().get(group) ?? []).map((r) => r.id);
  }

  /** Drop the conditional-request cache (after a logout, or a dictionary bump). */
  clearCache(): void {
    this.#cache.clear();
  }

  /**
   * The absolute URL a route resolves to — used by `fn.csvUrl()` / `watchlists.exportCsvUrl()`,
   * which navigate the browser rather than fetching (API.md L1264).
   */
  url(routeId: string, args: AnyRouteArgs = {}): string {
    const traceId = this.#traceId();
    const route = this.#route(routeId, traceId);
    return this.#url(route, args.params, args.query, traceId);
  }

  /** Typed request — `RouteId`, `RouteArgs` and the response all come from the barrel. */
  request<Id extends RouteId>(
    route: Id,
    args?: RouteArgs<RouteDefOf<Id>>,
    init?: RequestOptions,
  ): Promise<RouteResponse<Id>> {
    return this.call(route, args, init) as Promise<RouteResponse<Id>>;
  }

  /** Untyped request, for the convenience namespaces and for callers holding a string id. */
  async call(
    routeId: string,
    args: AnyRouteArgs = {},
    init: RequestOptions = {},
  ): Promise<unknown> {
    const traceId = init.traceId ?? this.#traceId();
    const route = this.#route(routeId, traceId);
    const params = this.#validate(route, 'params', args.params, traceId);
    const query = this.#validate(route, 'query', args.query, traceId);
    const raw = isRawBody(args.body);
    const body = raw ? args.body : this.#validate(route, 'body', args.body, traceId);
    const url = this.#url(route, params, query, traceId);

    const headers: Record<string, string> = {
      accept: init.accept ?? route.accept ?? 'application/json',
      'x-trace-id': traceId,
      'x-client-version': this.options.clientVersion,
    };
    if (this.options.token !== undefined && this.options.token !== '') {
      headers.authorization = `Bearer ${this.options.token}`;
    } else if (!SAFE_METHODS.has(route.method)) {
      // Cookie mode: CSRF defence of API.md §0 L59.
      headers['x-requested-with'] = 'terminal';
    }
    if (body !== undefined && !raw) headers['content-type'] = 'application/json';
    for (const [k, v] of Object.entries(this.options.headers ?? {})) headers[k.toLowerCase()] = v;
    for (const [k, v] of Object.entries(init.headers ?? {})) headers[k.toLowerCase()] = v;

    const cacheable = route.etag && this.options.cacheEtags !== false;
    const cacheKey = `${route.id} ${url}`;
    const cached = cacheable ? this.#cache.get(cacheKey) : undefined;
    if (cached !== undefined) headers['if-none-match'] = cached.etag;

    const request: RequestInit = {
      method: route.method,
      headers,
      ...(body === undefined ? {} : { body: raw ? (body as BodyInit) : JSON.stringify(body) }),
      ...(init.signal ? { signal: init.signal } : {}),
      ...(this.options.token !== undefined && this.options.token !== ''
        ? {}
        : { credentials: this.options.credentials ?? 'include' }),
    };

    const started = now();
    let res: Response;
    try {
      res = await this.#fetch(url, request);
    } catch (err) {
      if (err instanceof Error && err.name === 'AbortError') throw err;
      const ms = now() - started;
      this.#trace({ traceId, route: route.id, ms, status: 0, errorCode: 'PROVIDER_UNAVAILABLE' });
      throw new TerminalApiError({
        code: 'PROVIDER_UNAVAILABLE',
        message: `network error calling ${route.method} ${route.path}: ${
          err instanceof Error ? err.message : String(err)
        }`,
        status: 0,
        traceId,
        retryable: true,
        details: { kind: 'network' },
        route: route.id,
        cause: err,
      });
    }
    const ms = now() - started;
    const responseTraceId = res.headers.get('x-trace-id') ?? traceId;
    this.#version_(res.headers);

    const quota = parseQuota(res.headers);
    const deprecated = res.headers.get('x-deprecated-fields');
    const traceEvent: TraceEvent = {
      traceId: responseTraceId,
      route: route.id,
      ms,
      status: res.status,
      ...(quota ? { quota } : {}),
      ...(deprecated
        ? {
            deprecatedFields: deprecated
              .split(',')
              .map((s) => s.trim())
              .filter(Boolean),
          }
        : {}),
      ...(res.status === 304 ? { cached: true } : {}),
    };

    if (res.status === 304) {
      if (cached === undefined) {
        this.#trace({ ...traceEvent, errorCode: 'INTERNAL' });
        throw new TerminalApiError({
          code: 'INTERNAL',
          message: `304 Not Modified for ${route.id} without a cached response`,
          status: 304,
          traceId: responseTraceId,
          route: route.id,
        });
      }
      this.#trace(traceEvent);
      return cached.value;
    }

    if (init.onResponseHeaders) init.onResponseHeaders(headersOf(res));

    const text = await res.text();

    if (!res.ok) {
      const error = this.#error(route, res, text, responseTraceId);
      this.#trace({ ...traceEvent, errorCode: error.code });
      throw error;
    }
    this.#trace(traceEvent);

    const contentType = res.headers.get('content-type') ?? '';
    if (contentType !== '' && !contentType.includes('json')) {
      // The §9 CSV exports. `wire/rest/export.ts` types them as `CsvDocument` (a `z.string()`),
      // so a route that declares a schema gets the validated text; one that does not gets the text
      // plus every response header (`content-disposition`, `x-provenance`, `x-as-of-*`).
      if (route.response !== null && init.skipResponseValidation !== true) {
        return this.#parseResponse(route, text, res.status, responseTraceId);
      }
      const out: TextResponse = { text, headers: headersOf(res) };
      return out;
    }

    if (text.trim() === '') return undefined;

    let json: unknown;
    try {
      json = JSON.parse(text) as unknown;
    } catch (err) {
      throw new TerminalApiError({
        code: 'VALIDATION_FAILED',
        message: `${route.id}: response was not valid JSON`,
        status: res.status,
        traceId: responseTraceId,
        details: { location: 'response' },
        route: route.id,
        cause: err,
      });
    }

    const value =
      route.response === null || init.skipResponseValidation === true
        ? json
        : this.#parseResponse(route, json, res.status, responseTraceId);

    if (cacheable) {
      const etag = res.headers.get('etag');
      if (etag !== null) this.#cache.set(cacheKey, { etag, value });
    }
    return value;
  }

  // ── internals ────────────────────────────────────────────────────────────

  #traceId(): string {
    const factory = this.options.traceId;
    return factory ? factory() : defaultTraceId();
  }

  #trace(event: TraceEvent): void {
    const sink = this.options.onTrace;
    if (!sink) return;
    try {
      sink(event);
    } catch {
      // a broken telemetry sink must never fail a request
    }
  }

  #version_(headers: Headers): void {
    const sink = this.options.onVersion;
    if (!sink) return;
    const serverVersion = headers.get('x-server-version');
    if (serverVersion === null) return;
    const next: VersionEvent = {
      serverVersion,
      minClientVersion: headers.get('x-min-client-version') ?? '',
      dictionaryVersion: headers.get('x-dictionary-version') ?? '',
    };
    const prev = this.#version;
    if (
      prev !== null &&
      prev.serverVersion === next.serverVersion &&
      prev.minClientVersion === next.minClientVersion &&
      prev.dictionaryVersion === next.dictionaryVersion
    ) {
      return;
    }
    this.#version = next;
    try {
      sink(next);
    } catch {
      // as above
    }
  }

  #route(routeId: string, traceId: string): IndexedRoute {
    const route = routes().get(routeId);
    if (route === undefined) {
      throw new TerminalApiError({
        code: 'NOT_FOUND',
        message: `unknown route '${routeId}' — wire/rest declares ${routes().size} routes`,
        status: 0,
        traceId,
        route: routeId,
      });
    }
    return route;
  }

  #validate(
    route: IndexedRoute,
    part: 'params' | 'query' | 'body',
    value: unknown,
    traceId: string,
  ): unknown {
    const schema = route[part];
    if (schema === null) return value;
    const input = value === undefined && part !== 'body' ? {} : value;
    const parsed = schema.safeParse(input);
    if (!parsed.success) {
      throw new TerminalApiError({
        code: 'VALIDATION_FAILED',
        message: `${route.id}: invalid request ${part}`,
        status: 0,
        traceId,
        details: { location: part, issues: issuesOf(parsed.error) },
        route: route.id,
      });
    }
    return parsed.data;
  }

  #parseResponse(route: IndexedRoute, json: unknown, status: number, traceId: string): unknown {
    const parsed = route.response!.safeParse(json);
    if (!parsed.success) {
      throw new TerminalApiError({
        code: 'VALIDATION_FAILED',
        message: `${route.id}: response did not match the wire schema`,
        status,
        traceId,
        details: { location: 'response', issues: issuesOf(parsed.error) },
        route: route.id,
      });
    }
    return parsed.data;
  }

  #error(route: IndexedRoute, res: Response, text: string, traceId: string): TerminalApiError {
    let json: unknown;
    try {
      json = text.trim() === '' ? undefined : (JSON.parse(text) as unknown);
    } catch {
      json = undefined;
    }
    const envelope = ErrorEnvelope.safeParse(json);
    if (envelope.success) {
      const e = envelope.data.error;
      return new TerminalApiError({
        code: e.code,
        message: e.message,
        status: res.status,
        traceId: e.traceId,
        retryable: e.retryable,
        retryAfterMs: e.retryAfterMs ?? this.#retryAfter(res),
        details: e.details,
        route: route.id,
      });
    }
    const message =
      isRecord(json) && isRecord(json.error) && typeof json.error.message === 'string'
        ? json.error.message
        : text.trim() === ''
          ? `${res.status} ${res.statusText}`
          : text.slice(0, 500);
    return new TerminalApiError({
      code: codeForStatus(res.status),
      message: `${route.id}: ${message}`,
      status: res.status,
      traceId,
      retryAfterMs: this.#retryAfter(res),
      route: route.id,
    });
  }

  #retryAfter(res: Response): number | undefined {
    const header = res.headers.get('retry-after');
    if (header === null) return undefined;
    const seconds = Number(header);
    return Number.isFinite(seconds) ? seconds * 1000 : undefined;
  }

  #url(route: IndexedRoute, params: unknown, query: unknown, traceId: string): string {
    const bag = isRecord(params) ? params : {};
    const withParams = route.spelling.replace(
      /:([A-Za-z0-9_]+)|\{([A-Za-z0-9_]+)\}/g,
      (_m: string, a: string | undefined, b: string | undefined): string => {
        const key = a ?? b ?? '';
        const value = bag[key];
        if (value === undefined || value === null) {
          throw new TerminalApiError({
            code: 'VALIDATION_FAILED',
            message: `${route.id}: missing path parameter '${key}'`,
            status: 0,
            traceId,
            details: { location: 'params', param: key },
            route: route.id,
          });
        }
        return encodeURIComponent(scalar(value));
      },
    );
    const search = new URLSearchParams();
    if (isRecord(query)) {
      for (const [key, value] of Object.entries(query)) {
        if (value === undefined || value === null) continue;
        if (Array.isArray(value)) {
          for (const item of value) {
            if (item === undefined || item === null) continue;
            search.append(key, scalar(item));
          }
        } else {
          search.append(key, scalar(value));
        }
      }
    }
    const qs = search.toString();
    return `${this.baseUrl}${withParams}${qs === '' ? '' : `?${qs}`}`;
  }
}

// ---------------------------------------------------------------------------
// TerminalClient — the convenience surface (API.md §10 L1241-1282)
// ---------------------------------------------------------------------------

/**
 * One namespace method per route in a group: `Rest.Auth.Login` → `client.auth.login(args)`.
 * Derived from the barrel, so a new route is callable the moment the generator runs.
 */
export type GroupApi<G> = {
  [K in keyof G as G[K] extends RouteLike ? Uncapitalize<K & string> : never]: (
    args?: RouteArgs<G[K]>,
    init?: RequestOptions,
  ) => Promise<RouteResponseOf<G[K]>>;
};

/** `'Auth' | 'Data' | 'Functions' | …` — the group half of every dotted route id. */
export type GroupName = RouteId extends `${infer G}.${string}` ? G : never;

/** The names API.md §10 uses for four of the groups. */
export const GROUP_ALIASES = {
  ref: 'Reference',
  fn: 'Functions',
  messaging: 'Messages',
  workspace: 'Workspaces',
} as const;
export type GroupAliases = typeof GROUP_ALIASES;

export type RestNamespaces = {
  [G in GroupName as Uncapitalize<G>]: GroupApi<GroupOf<G>>;
} & {
  [A in keyof GroupAliases as GroupAliases[A] extends GroupName ? A : never]: GroupApi<
    GroupOf<Extract<GroupAliases[A], string>>
  >;
};

/** The transport-and-dictionary half of API.md §10's `TerminalClient`. */
export interface TerminalClientCore {
  /** raw typed transport — every route in the barrel. */
  readonly rest: RestClient;
  /** WebSocket client (§6). Constructed on first access; WP-13 implements it. */
  readonly live: LiveClient;
  /** dictionary + `format()` (API-07). */
  readonly fields: FieldsApi;
  /** re-export of the core function registry (manifests: params, paramGrammar, live(), csv, help). */
  readonly functions: FunctionRegistry;
  readonly options: Readonly<ClientOptions>;
  status(): Promise<unknown>;
  health(): Promise<unknown>;
  /** closes the WS (when one was opened). */
  close(): void;
}

export type TerminalClient = TerminalClientCore & RestNamespaces;

function buildNamespaces(rest: RestClient): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {};
  for (const [group, list] of groups()) {
    const api: Record<string, unknown> = {};
    for (const route of list) {
      api[uncapitalise(route.name)] = (
        args?: AnyRouteArgs,
        init?: RequestOptions,
      ): Promise<unknown> => rest.call(route.id, args, init);
    }
    out[uncapitalise(group)] = api;
  }
  for (const [alias, group] of Object.entries(GROUP_ALIASES)) {
    const api = out[uncapitalise(group)];
    if (api !== undefined) out[alias] = api;
  }
  return out;
}

/** API.md §10 L1239. */
export function createClient(opts: ClientOptions): TerminalClient {
  const rest = new RestClient(opts);
  const fields = createFieldsApi({
    rest,
    ...(opts.fieldsSeed ? { seed: opts.fieldsSeed } : {}),
    ...(opts.format ? { format: opts.format } : {}),
  });

  // `LiveClient` is a WP-13 stub whose constructor throws: build it only when `client.live` (or
  // anything that needs the socket) is actually touched, so REST-only callers are unaffected.
  let live: LiveClient | null = null;

  const client: Record<string, unknown> = { ...buildNamespaces(rest) };
  Object.assign(client, {
    rest,
    fields,
    functions: registry,
    options: rest.options,
    status: (): Promise<unknown> => callByPath(rest, 'GET', '/status'),
    health: (): Promise<unknown> => callByPath(rest, 'GET', '/health'),
    close: (): void => {
      if (live !== null) live.close();
    },
  });
  Object.defineProperty(client, 'live', {
    enumerable: true,
    configurable: true,
    get(): LiveClient {
      live ??= new LiveClient(rest.options);
      return live;
    },
  });
  return client as unknown as TerminalClient;
}

function callByPath(rest: RestClient, method: HttpMethod, path: string): Promise<unknown> {
  const id = rest.routeIdFor(method, path);
  if (id === undefined) {
    return Promise.reject(
      new TerminalApiError({
        code: 'NOT_FOUND',
        message: `wire/rest declares no route for ${method} ${path}`,
        status: 0,
        traceId: defaultTraceId(),
      }),
    );
  }
  return rest.call(id);
}
