// packages/core/src/fields/defs/reference.ts — field_class 'reference'
//
// Descriptive, slowly-changing terms of an instrument or of a membership: what the contract is,
// not what it is worth. Every one of them is bitemporal (`pit: true`) unless it is a property of a
// contract that cannot be restated.

import type { FieldDef } from '../../types/fields.js';

type FieldSource = FieldDef['sources'][number];

const src = (
  assetClass: FieldSource['assetClass'],
  sourceId: string,
  endpoint: string,
  providerPath: string,
): FieldSource => ({ assetClass, sourceId, endpoint, providerPath });

const SINCE = '2026.09.1';
const REMOVE_AFTER = '2027.01.1';

export const referenceFields: readonly FieldDef[] = [
  {
    id: 'EQY_SH_OUT',
    label: 'Shares outstanding',
    definition:
      'Number of common shares issued and outstanding as reported on the cover page of the most ' +
      'recent periodic filing known at knownAt. Not adjusted for splits after that filing date.',
    type: 'number',
    unit: 'shares',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [
      src(
        'equity',
        'sec.companyfacts',
        'companyfacts',
        'facts.dei.EntityCommonStockSharesOutstanding',
      ),
    ],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 14840392000, asOf: '2026-08-01' },
    since: SINCE,
  },
  {
    id: 'CPN_FREQ',
    label: 'Coupon frequency',
    definition:
      'Number of coupon payments per year fixed by the terms of the issue: 2 for a US Treasury ' +
      'note or bond, 0 for a discount bill.',
    type: 'integer',
    unit: 'count',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].interestPaymentFrequency')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 2, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_STRIKE_PX',
    label: 'Strike price',
    definition: 'Exercise price of the option series, in the contract currency.',
    type: 'number',
    unit: 'price',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.options[].option')],
    updateFreq: 'static',
    pit: false,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 350, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_EXPIRE_DT',
    label: 'Expiration date',
    definition:
      'Last date on which the option may be exercised, parsed from the OCC symbol; the expiry cut ' +
      'itself is a property of the venue, not of this field.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.options[].option')],
    updateFreq: 'static',
    pit: false,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: '2026-12-19', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_PUT_CALL',
    label: 'Put/call',
    definition: 'Whether the series is a call (C) or a put (P), from the OCC symbol.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['C', 'P'],
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.options[].option')],
    updateFreq: 'static',
    pit: false,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'C', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_CONT_SIZE',
    label: 'Contract size',
    definition:
      'Number of underlying units one contract delivers — 100 shares for a standard US equity ' +
      'option, less after an adjustment for a corporate action.',
    type: 'integer',
    unit: 'shares',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].contract_size')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 100, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_UNDL_TICKER',
    label: 'Underlying ticker',
    definition:
      'Display ticker of the instrument the option delivers, as the terminal resolves it — the ' +
      'root symbol of the OCC code mapped back onto a loadable security.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.symbol')],
    updateFreq: 'static',
    pit: false,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'AAPL US Equity', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_WEIGHT',
    label: 'Index weight',
    definition:
      'Weight of the member in the index as of the effective date of the holdings file, expressed ' +
      'as a fraction of the index (0.0712 = 7.12 %).',
    type: 'number',
    unit: 'ratio',
    decimals: 6,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [
      src('index', 'sec.archives', 'archives', 'invstOrSec[].pctVal'),
      src('etf', 'ssga.holdings', 'holdings', 'rows[].Weight'),
    ],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: 0.0712, asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_SHARES',
    label: 'Index shares held',
    definition:
      'Share count of the member held by the index vehicle at the effective date of the holdings ' +
      'file; the basis of the weight when the index is share-weighted.',
    type: 'number',
    unit: 'shares',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [
      src('index', 'sec.archives', 'archives', 'invstOrSec[].balance'),
      src('etf', 'ssga.holdings', 'holdings', 'rows[].Shares Held'),
    ],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: 173920000, asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_SINCE',
    label: 'Member since',
    definition:
      'First date on which the member appears in the index membership history the terminal holds. ' +
      'It is the start of the bitemporal membership row, not an index-provider announcement date.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [src('index', 'sec.archives', 'archives', 'filing.periodOfReport')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: '2013-04-30', asOf: '2026-08-31' },
    since: SINCE,
  },

  // ── Identifiers (REF-01) ────────────────────────────────────────────────────────────────────
  {
    id: 'ID_BB_GLOBAL',
    label: 'Composite FIGI',
    definition:
      'OpenFIGI composite-level FIGI of the instrument — the 12-character identity of the ' +
      'composite ticker, stable across venue and across a ticker change.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'govt', 'option'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].compositeFIGI')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'BBG000B9XRY4', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_BB_SHARE_CLASS',
    label: 'Share class FIGI',
    definition:
      'OpenFIGI share-class-level FIGI of the issue: the same value for every composite and ' +
      'venue listing of one share class worldwide.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].shareClassFIGI')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'BBG001S5N8V8', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_FIGI_LISTING',
    label: 'Listing FIGI',
    definition:
      'OpenFIGI venue-level FIGI of the primary listing (the `UW`, `UN`, `UP` line), as opposed ' +
      'to the composite FIGI carried by ID_BB_GLOBAL.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].figi')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'BBG001S5N8V8', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_ISIN',
    label: 'ISIN',
    definition:
      'ISO 6166 International Securities Identification Number of the issue: two-letter country ' +
      'prefix, nine-character NSIN and a Luhn check digit over the letter expansion.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].isin')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'US0378331005', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_CUSIP',
    label: 'CUSIP',
    definition:
      'Nine-character CUSIP of the issue, the last character being the mod-10 double-add-double ' +
      'check digit; the loadable ticker of a US Treasury.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [
      src('equity', 'openfigi.mapping', 'mapping', 'data[].cusip'),
      src('govt', 'treasury.bills', 'bills', 'securities[].cusip'),
    ],
    updateFreq: 'static',
    pit: true,
    example: { ref: '912797VE4 Govt', value: '912797VE4', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_SEDOL',
    label: 'SEDOL',
    definition:
      'Seven-character SEDOL of the issue, the last character being the 1-3-1-7-3-9 weighted ' +
      'check digit.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].sedol')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2046251', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_CIK',
    label: 'CIK',
    definition:
      'SEC Central Index Key of the issuer, zero-padded to ten digits as `data.sec.gov` returns ' +
      'it; the unpadded form is what `/Archives` paths take (§18.6).',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.tickers', 'tickers', 'data[].cik_str')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '0000320193', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_LEI',
    label: 'LEI',
    definition:
      'ISO 17442 Legal Entity Identifier of the issuer: twenty characters identifying the legal ' +
      'person, not the security.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'ein')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'HWUPKR0MPOU8FGXBT394', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_OCC',
    label: 'OCC contract symbol',
    definition:
      'OCC option symbol in the Cboe form the feed publishes, root unpadded: ' +
      '`AAPL260916C00245000` — root, YYMMDD expiry, C/P and the strike in thousandths.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.options[].option')],
    updateFreq: 'static',
    pit: false,
    example: {
      ref: 'AAPL US 12/19/26 C350 Equity',
      value: 'AAPL261219C00350000',
      asOf: '2026-09-15',
    },
    since: SINCE,
  },
  {
    id: 'ID_TICKER',
    label: 'Ticker',
    definition:
      'Composite-level ticker the user types on the command line (`AAPL`, `SPX`, `EURUSD`, a ' +
      'Treasury CUSIP). Never an identity on its own: a ticker is reused across time (REF-01).',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.ticker')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'AAPL', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ID_EXCH_TICKER',
    label: 'Local ticker',
    definition:
      'Symbol the primary venue itself uses for the listing, which may differ from the composite ' +
      'ticker (class suffixes, dot and dash conventions).',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'securityMaster', 'listings.local_ticker')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'BRK/B US Equity', value: 'BRK.B', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'PARSEKYABLE_DES',
    label: 'Command-line reference',
    definition:
      'The security exactly as the command line accepts and re-formats it — `AAPL US Equity`, ' +
      '`SPX Index`, `EURUSD Curncy`, `912797VE4 Govt` — ticker, exchange code and market sector.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.ticker')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'AAPL US Equity', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Names, type and status ──────────────────────────────────────────────────────────────────
  {
    id: 'NAME',
    label: 'Name',
    definition:
      'Display name of the instrument as the terminal shows it in a panel title, a search result ' +
      'and a CSV header — the short form, not the legal name.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.name')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Apple Inc', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'LONG_COMP_NAME',
    label: 'Issuer legal name',
    definition:
      'Registered legal name of the issuing entity as the filer reports it, including the legal ' +
      'suffix that `text/normName.ts` strips when it matches names.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'name')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Apple Inc.', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ISSUER_TYPE',
    label: 'Issuer type',
    definition:
      'What kind of legal person issued the security: an operating company, a fund, a sovereign, ' +
      'an index provider, a central bank, or anything else.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['operating', 'fund', 'sovereign', 'index_provider', 'central_bank', 'other'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'govt', 'rate'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'issuers.entity_type')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'operating', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SECURITY_TYP',
    label: 'Security type',
    definition:
      'Provider security type of the issue as OpenFIGI classifies it: `Common Stock`, `ETP`, ' +
      '`REIT`, `Index`, `Spot`, `US GOVERNMENT`, `Equity Option`.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option'],
    sources: [src('*', 'openfigi.mapping', 'mapping', 'data[].securityType')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Common Stock', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'MARKET_SECTOR_DES',
    label: 'Market sector',
    definition:
      'Sector word that closes a command-line reference and disambiguates a ticker: one of the ' +
      'eleven market sectors the parser accepts (`Equity`, `Index`, `Curncy`, `Govt`, …).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: [
      'Equity',
      'Index',
      'Curncy',
      'Govt',
      'Corp',
      'Comdty',
      'Mtge',
      'Muni',
      'Pfd',
      'M-Mkt',
      'Crypto',
    ],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.market_sector')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Equity', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ASSET_CLASS',
    label: 'Asset class',
    definition:
      'Internal asset class that chooses the function variant and the entitlement row: one of the ' +
      'ten values `equity`, `etf`, `index`, `fx`, `govt`, `option`, `future`, `crypto`, `rate`, `econ`.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: [
      'equity',
      'etf',
      'index',
      'fx',
      'govt',
      'option',
      'future',
      'crypto',
      'rate',
      'econ',
    ],
    fieldClass: 'reference',
    assetClasses: [
      'equity',
      'etf',
      'index',
      'fx',
      'govt',
      'option',
      'future',
      'crypto',
      'rate',
      'econ',
    ],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.asset_class')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'equity', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SECURITY_STATUS',
    label: 'Security status',
    definition:
      'Lifecycle state of the instrument: tradeable, delisted, not yet trading, matured (a bond) ' +
      'or expired (a contract). SECF filters on it; `STATUS=all` lifts the default active filter.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['active', 'delisted', 'pending', 'matured', 'expired'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.status')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'active', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Sector and classification codes (REF-07) ────────────────────────────────────────────────
  {
    id: 'GICS_SECTOR_CODE',
    label: 'GICS sector code',
    definition:
      'Two-digit GICS level-1 sector code assigned to the issuer, e.g. `45` Information Technology.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sector')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '45', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'GICS_SECTOR_NAME',
    label: 'GICS sector',
    definition: 'Name of the GICS level-1 sector, the grouping MEMB subtotals and SECF facets by.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sector')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Information Technology', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'GICS_INDUSTRY_GROUP_NAME',
    label: 'GICS industry group',
    definition: 'Name of the GICS level-2 industry group (four-digit code) the issuer sits in.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sub-Industry')],
    updateFreq: 'monthly',
    pit: true,
    example: {
      ref: 'AAPL US Equity',
      value: 'Technology Hardware & Equipment',
      asOf: '2026-09-15',
    },
    since: SINCE,
  },
  {
    id: 'GICS_INDUSTRY_CODE',
    label: 'GICS industry code',
    definition: 'Six-digit GICS level-3 industry code assigned to the issuer.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sub-Industry')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '452020', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'GICS_INDUSTRY_NAME',
    label: 'GICS industry',
    definition: 'Name of the GICS level-3 industry the issuer is classified into.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sub-Industry')],
    updateFreq: 'monthly',
    pit: true,
    example: {
      ref: 'AAPL US Equity',
      value: 'Technology Hardware, Storage & Peripherals',
      asOf: '2026-09-15',
    },
    since: SINCE,
  },
  {
    id: 'GICS_SUB_INDUSTRY_NAME',
    label: 'GICS sub-industry',
    definition:
      'Name of the GICS level-4 sub-industry, the finest classification the terminal stores.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'wiki.sp500', 'constituents', 'rows[].GICS Sub-Industry')],
    updateFreq: 'monthly',
    pit: true,
    example: {
      ref: 'AAPL US Equity',
      value: 'Technology Hardware, Storage & Peripherals',
      asOf: '2026-09-15',
    },
    since: SINCE,
  },
  {
    id: 'SIC_CODE',
    label: 'SIC code',
    definition:
      'Four-digit Standard Industrial Classification code the SEC files the issuer under.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'sic')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '3571', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SIC_DESCRIPTION',
    label: 'SIC description',
    definition: 'SEC wording of the SIC code, shown beside it on DES so the number is readable.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'sicDescription')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Electronic Computers', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Exchange, MIC and listing ───────────────────────────────────────────────────────────────
  {
    id: 'EXCH_CODE',
    label: 'Exchange code',
    definition:
      'OpenFIGI composite exchange code that follows the ticker on the command line — `US` for a ' +
      'US composite, `GOVT`, `FX`, `INDEX`, `RATE`, `ECON`, `CRYPTO` for the non-listed classes.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto', 'rate', 'econ'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.exch_code')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'US', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'PRIM_EXCH_MIC',
    label: 'Primary exchange MIC',
    definition: 'ISO 10383 market identifier code of the venue that carries the primary listing.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'option'],
    sources: [src('equity', 'internal.derived', 'securityMaster', 'listings.mic')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'XNAS', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'PRIM_EXCH_NAME',
    label: 'Primary exchange',
    definition: 'Name of the venue behind PRIM_EXCH_MIC, as the exchange register spells it.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'option'],
    sources: [src('equity', 'internal.derived', 'securityMaster', 'exchanges.name')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'Nasdaq Stock Market', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'EXCH_TIMEZONE',
    label: 'Exchange time zone',
    definition:
      'IANA time zone of the primary venue; every session time on a screen is rendered in it ' +
      'unless the user has asked for local time.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'option'],
    sources: [src('equity', 'internal.derived', 'securityMaster', 'exchanges.tz')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'America/New_York', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'EXCH_CALENDAR_ID',
    label: 'Trading calendar',
    definition:
      'Identifier of the trading calendar (REF-06) whose holidays and early closes govern the ' +
      'instrument: `XNYS`, `XNAS`, `XCBO`, `SIFMA`, `USGOVT`, `FX_USD`.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option'],
    sources: [src('*', 'internal.derived', 'calendars', 'exchanges.calendar_id')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'XNAS', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'LISTING_STATUS',
    label: 'Listing status',
    definition:
      'State of the primary listing at the venue — trading, suspended or delisted — which can ' +
      'differ from SECURITY_STATUS when only one of several venues has stopped.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['active', 'suspended', 'delisted'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'securityMaster', 'listings.listing_status')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'active', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'FIRST_TRADE_DT',
    label: 'First trade date',
    definition:
      'Earliest session for which the terminal holds a price for the instrument; the left edge of ' +
      'every chart and the floor of a GP range request.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'crypto'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].meta.firstTradeDate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '1980-12-12', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Issue attributes: currency, country, par ────────────────────────────────────────────────
  {
    id: 'CRNCY',
    label: 'Currency',
    definition:
      'ISO 4217 code of the currency the instrument trades and settles in; every price and ' +
      'currency-unit field on the screen is in it unless a field says otherwise.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'index', 'fx', 'govt', 'option', 'crypto'],
    sources: [src('*', 'internal.derived', 'securityMaster', 'instruments.currency')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'USD', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'CNTRY_OF_DOMICILE',
    label: 'Country of domicile',
    definition: 'ISO 3166-1 alpha-2 country in which the issuing entity is domiciled.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'addresses.business.stateOrCountry')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'US', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'CNTRY_OF_ISSUE',
    label: 'Country of issue',
    definition:
      'ISO 3166-1 alpha-2 country the security was issued in — the ISIN prefix, which need not ' +
      'equal the domicile of the issuer.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'openfigi.mapping', 'mapping', 'data[].isin')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'US', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'STATE_OF_INCORPORATION',
    label: 'State of incorporation',
    definition: 'US state or foreign jurisdiction under whose law the issuer is incorporated.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'stateOfIncorporation')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'CA', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'PAR_VALUE',
    label: 'Par value',
    definition:
      'Nominal value of one unit of the issue in the issue currency: the stated par of a share, ' +
      'or the redemption face of a bond (100 for a US Treasury).',
    type: 'number',
    unit: 'ccy',
    decimals: 6,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].parValue')],
    updateFreq: 'static',
    pit: true,
    example: { ref: '912797VE4 Govt', value: 100, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'FISCAL_YEAR_END',
    label: 'Fiscal year end',
    definition:
      'Month and day on which the issuer closes its financial year, as `MMDD` — `0926` for a ' +
      'late-September year end. It fixes which quarter a filing belongs to.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'fiscalYearEnd')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '0926', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'COMPANY_WEB_ADDRESS',
    label: 'Website',
    definition: 'Public website of the issuer as recorded on its SEC submissions record.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.submissions', 'submissions', 'website')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'https://www.apple.com', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Treasury / fixed-income terms (REF-04) ──────────────────────────────────────────────────
  {
    id: 'BOND_TYPE',
    label: 'Bond type',
    definition:
      'Treasury instrument family the terms belong to: a discount `bill`, a `note`, a `bond`, an ' +
      'inflation-linked `tips` or a floating-rate `frn`. It chooses the pricing convention.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['bill', 'note', 'bond', 'tips', 'frn'],
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].securityType')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 'note', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'CPN',
    label: 'Coupon',
    definition:
      'Annual coupon rate fixed by the terms of the issue, in percent of par; null for a discount ' +
      'bill, the current reset rate for a floating-rate note.',
    type: 'number',
    unit: 'pct',
    decimals: 3,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].interestRate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 4.25, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'CPN_TYP',
    label: 'Coupon type',
    definition:
      'How the coupon is determined: `fixed`, `zero` (a bill), `float` (an FRN over a reference ' +
      'index), `step` or `inflation_linked` (TIPS).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['fixed', 'zero', 'float', 'step', 'inflation_linked'],
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].interestPaymentFrequency')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 'fixed', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'MATURITY',
    label: 'Maturity date',
    definition:
      'Date on which the principal is repaid and the security stops accruing. It closes every ' +
      'cash-flow schedule and is the anchor of the yield and duration calculations.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].maturityDate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '2035-11-15', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ISSUE_DT',
    label: 'Issue date',
    definition: 'Date the security was first settled to buyers at auction.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].issueDate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '2025-11-17', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'DATED_DT',
    label: 'Dated date',
    definition:
      'Date from which interest begins to accrue, which for a reopened issue is earlier than the ' +
      'issue date and is what the accrued-interest calculation starts from.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].datedDate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '2025-11-15', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'DAY_CNT',
    label: 'Day count',
    definition:
      'Day-count convention of the issue — `ACT/ACT` for Treasury notes and bonds, `ACT/360` for ' +
      'bills — which fixes how accrual and discounting count days (ANAL-01).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['ACT/ACT', 'ACT/360', 'ACT/365F', '30/360', '30E/360', 'ACT/ACT-ISDA'],
    fieldClass: 'reference',
    assetClasses: ['govt', 'rate'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.day_count')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 'ACT/ACT', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'FIRST_CPN_DT',
    label: 'First coupon date',
    definition:
      'Date of the first coupon paid by the issue. When it is not one full period after the dated ' +
      'date, the first period is short or long and the schedule is built backwards from maturity.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].firstInterestPaymentDate')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '2026-05-15', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'NXT_CPN_DT',
    label: 'Next coupon date',
    definition:
      'First scheduled coupon date strictly after the valuation date, taken from the generated ' +
      'schedule; it closes the current accrual period.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'internal.derived', 'analytics', 'schedule.nextCouponDate')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '2026-11-15', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SECURITY_TERM',
    label: 'Original term',
    definition:
      'Term of the issue at auction as the Treasury labels it: `4-Week`, `13-Week`, `2-Year`, ' +
      '`10-Year`, `30-Year`. It is the original term, not the remaining life.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].securityTerm')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: '10-Year', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'AMT_OUTSTANDING',
    label: 'Amount outstanding',
    definition:
      'Face amount of the issue currently outstanding, in the issue currency, including every ' +
      'reopening known at knownAt.',
    type: 'number',
    unit: 'ccy',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].totalAccepted')],
    updateFreq: 'on_filing',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 42000000000, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'MIN_PIECE',
    label: 'Minimum denomination',
    definition:
      'Smallest face amount that may be held, in the issue currency (100 for a US Treasury).',
    type: 'number',
    unit: 'ccy',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].minimumBidAmount')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 100, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'MIN_INCREMENT',
    label: 'Minimum increment',
    definition: 'Face amount by which a holding above the minimum denomination may be increased.',
    type: 'number',
    unit: 'ccy',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'treasury.bills', 'bills', 'securities[].multiplesToBid')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 100, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SETTLE_DAYS',
    label: 'Settlement days',
    definition:
      'Number of business days between trade and settlement, which is what turns a valuation date ' +
      'into the settlement date used for accrued interest and yield.',
    type: 'integer',
    unit: 'days',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['govt', 'equity', 'etf'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.settlement_days')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 1, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'BUSINESS_DAY_CONV',
    label: 'Business day convention',
    definition:
      'Rule that moves a scheduled date falling on a holiday: `following`, `modified_following`, ' +
      '`preceding`, or `none` for a Treasury, whose dates are unadjusted.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['following', 'modified_following', 'preceding', 'none'],
    fieldClass: 'reference',
    assetClasses: ['govt', 'rate'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.business_day_conv')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 'following', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'SETTLE_CALENDAR',
    label: 'Settlement calendar',
    definition:
      'Calendar (REF-06) whose holidays the settlement and coupon dates are rolled against — ' +
      '`SIFMA` for US Treasuries.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt', 'rate'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.calendar_id')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: 'SIFMA', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'IS_CALLABLE',
    label: 'Callable',
    definition:
      'True when the issuer may redeem the issue before maturity under a call schedule; false for ' +
      'every modern US Treasury.',
    type: 'boolean',
    unit: null,
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.is_callable')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: false, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'ON_THE_RUN',
    label: 'On the run',
    definition:
      'True when the issue is the most recently auctioned security of its term, and therefore the ' +
      'benchmark the curve and spread screens quote against.',
    type: 'boolean',
    unit: null,
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.on_the_run')],
    updateFreq: 'weekly',
    pit: true,
    example: { ref: 'T 4 1/4 11/15/35 Govt', value: true, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'REFERENCE_INDEX',
    label: 'Reference index',
    definition:
      'Floating-rate index a coupon resets against — `SOFR` for a Treasury FRN. Empty for a fixed ' +
      'coupon.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['govt', 'rate'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.reference_index')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'TF 0 01/31/28 Govt', value: 'SOFR', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'FLT_SPREAD',
    label: 'Floating spread',
    definition:
      'Spread added to the reference index at each reset of a floating-rate note, in basis points.',
    type: 'number',
    unit: 'bp',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.spread_bp')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'TF 0 01/31/28 Govt', value: 15.5, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'IDX_RATIO_BASE',
    label: 'Index ratio base',
    definition:
      'Reference CPI level at the dated date of an inflation-linked issue; today’s index ratio ' +
      'is the current reference CPI divided by it.',
    type: 'number',
    unit: 'ratio',
    decimals: 8,
    fieldClass: 'reference',
    assetClasses: ['govt'],
    sources: [src('govt', 'internal.derived', 'terms', 'govt_terms.index_ratio_base')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'TII 2 1/8 02/15/41 Govt', value: 312.4318, asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Option terms (REF-05) ───────────────────────────────────────────────────────────────────
  {
    id: 'OPT_ROOT',
    label: 'Option root',
    definition:
      'Root symbol of the option series as the OCC symbol carries it, unpadded in the Cboe form ' +
      'and padded to six characters in the OSI form.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.options', 'options', 'data.options[].option')],
    updateFreq: 'static',
    pit: false,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'AAPL', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_MULTIPLIER',
    label: 'Contract multiplier',
    definition:
      'Factor that turns one point of option price into currency — 100 for a standard listed ' +
      'equity option. Premium paid = price x multiplier.',
    type: 'integer',
    unit: 'count',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].multiplier')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 100, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_EXER_TYP',
    label: 'Exercise style',
    definition:
      'Whether the holder may exercise on any business day up to expiry (`american`) or only at ' +
      'expiry (`european`); it decides whether early exercise has to be priced.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['american', 'european'],
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].exercise_style')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'american', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_SETTLE_TYP',
    label: 'Settlement type',
    definition:
      'What exercise delivers: the underlying shares (`physical`) or a cash difference (`cash`, ' +
      'as for an index option).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['physical', 'cash'],
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].settlement')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'physical', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_AM_PM',
    label: 'AM/PM settlement',
    definition:
      'Whether the settlement price is struck from the opening prints (`am`, typical of quarterly ' +
      'index options) or the close (`pm`, the standard for listed equity options).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['am', 'pm'],
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].am_pm_settlement')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 'pm', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_TICK_SIZE',
    label: 'Tick size',
    definition: 'Smallest price increment the series may be quoted in, in the contract currency.',
    type: 'number',
    unit: 'price',
    decimals: 4,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].tick_size')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: 0.01, asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_LAST_TRADE_DT',
    label: 'Last trade date',
    definition:
      'Last session on which the series may be traded, which for a standard US equity option is ' +
      'the expiry itself and for an AM-settled series is the business day before it.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].last_trade_date')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: '2026-12-18', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'OPT_IS_WEEKLY',
    label: 'Weekly',
    definition:
      'True when the series is a weekly expiry rather than one of the monthly third-Friday ' +
      'expiries; OMON groups its chains separately.',
    type: 'boolean',
    unit: null,
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['option'],
    sources: [src('option', 'cboe.symbolBook', 'symbolBook', 'rows[].is_weekly')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'AAPL US 12/19/26 C350 Equity', value: false, asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Index membership (REF-07, MEMB) ─────────────────────────────────────────────────────────
  {
    id: 'IDX_MEMBER_MKT_VAL',
    label: 'Index market value held',
    definition:
      'Market value of the member held by the index vehicle at the effective date of the holdings ' +
      'file, in USD as the filing reports it.',
    type: 'number',
    unit: 'ccy',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [
      src('index', 'sec.archives', 'archives', 'invstOrSec[].valUSD'),
      src('etf', 'ssga.holdings', 'holdings', 'rows[].Market Value'),
    ],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: 51234567890.12, asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_ASOF',
    label: 'Membership as-of date',
    definition:
      'Effective date of the holdings file the weight and share count come from — the N-PORT ' +
      'reporting period end or the SSGA file date, not the date the file was published.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [src('index', 'sec.archives', 'archives', 'genInfo.repPdDate')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: '2026-06-30', asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_SOURCE',
    label: 'Membership source',
    definition:
      'Which feed the membership row came from: an N-PORT filing of the proxy fund (`sec.archives`) ' +
      'or the fund manager’s own holdings file (`ssga.holdings`).',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['sec.archives', 'ssga.holdings'],
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [src('index', 'internal.derived', 'securityMaster', 'index_members.source_id')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: 'sec.archives', asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_MEMBER_COUNT',
    label: 'Member count',
    definition:
      'Number of constituents the index has at the as-of date of its latest membership file.',
    type: 'integer',
    unit: 'count',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['index', 'etf'],
    sources: [src('index', 'internal.derived', 'securityMaster', 'index_members.count')],
    updateFreq: 'monthly',
    pit: true,
    example: { ref: 'SPX Index', value: 503, asOf: '2026-08-31' },
    since: SINCE,
  },
  {
    id: 'IDX_PROVIDER',
    label: 'Index provider',
    definition: 'Organisation that calculates and publishes the index.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['index'],
    sources: [src('index', 'internal.derived', 'securityMaster', 'indices.provider')],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'SPX Index', value: 'S&P Dow Jones Indices', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'IDX_PROXY_FUND',
    label: 'Membership proxy fund',
    definition:
      'Fund whose published holdings the terminal uses as the membership of the index, because the ' +
      'index provider does not publish constituents — SPY for SPX. Blank when none is needed.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['index'],
    sources: [
      src('index', 'internal.derived', 'securityMaster', 'indices.proxy_fund_instrument_id'),
    ],
    updateFreq: 'static',
    pit: true,
    example: { ref: 'SPX Index', value: 'SPY US Equity', asOf: '2026-09-15' },
    since: SINCE,
  },

  // ── Holders (HDS) ───────────────────────────────────────────────────────────────────────────
  {
    id: 'HLD_HOLDER_NAME',
    label: 'Holder',
    definition:
      'Name of the entity holding the position, as the filing that disclosed it spells it — a fund ' +
      'on an N-PORT row, the registrant on an insider form.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.archives', 'archives', 'genInfo.regName')],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'SPDR S&P 500 ETF Trust', asOf: '2026-06-30' },
    since: SINCE,
  },
  {
    id: 'HLD_SHARES_HELD',
    label: 'Shares held',
    definition: 'Share count the holder reported for the position at the as-of date of the filing.',
    type: 'number',
    unit: 'shares',
    decimals: 0,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [
      src('equity', 'sec.archives', 'archives', 'invstOrSec[].balance'),
      src('etf', 'ssga.holdings', 'holdings', 'rows[].Shares Held'),
    ],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 186540000, asOf: '2026-06-30' },
    since: SINCE,
  },
  {
    id: 'HLD_MKT_VAL',
    label: 'Position value',
    definition: 'Value of the reported position in USD at the as-of date of the filing.',
    type: 'number',
    unit: 'ccy',
    decimals: 2,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.archives', 'archives', 'invstOrSec[].valUSD')],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 42318900000, asOf: '2026-06-30' },
    since: SINCE,
  },
  {
    id: 'HLD_PCT_OUT',
    label: 'Percent outstanding held',
    definition:
      'Reported position as a percentage of shares outstanding at the same as-of date; null when ' +
      'the share count is not known for that date.',
    type: 'number',
    unit: 'pct',
    decimals: 3,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'holders', 'holders.pctOutstanding')],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 1.257, asOf: '2026-06-30' },
    since: SINCE,
  },
  {
    id: 'HLD_AS_OF_DT',
    label: 'Holding as-of date',
    definition:
      'Reporting-period end the holder’s position refers to. A holders table is always as of a ' +
      'filing date in the past, never live.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.archives', 'archives', 'genInfo.repPdDate')],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2026-06-30', asOf: '2026-08-31' },
    since: SINCE,
  },

  // ── Corporate actions (REF-09, DATA-08, CACS) ───────────────────────────────────────────────
  {
    id: 'CA_TYPE',
    label: 'Action type',
    definition:
      'What the corporate action is: a cash, special or stock dividend, a split or reverse split, ' +
      'a spinoff, merger, tender, rights issue, call, conversion, name or ticker change, a ' +
      'delisting or a capital return.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: [
      'cash_dividend',
      'special_dividend',
      'stock_dividend',
      'split',
      'reverse_split',
      'spinoff',
      'merger',
      'tender',
      'rights',
      'call',
      'conversion',
      'name_change',
      'ticker_change',
      'delisting',
      'capital_return',
    ],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].events.dividends')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'cash_dividend', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_STATUS',
    label: 'Action status',
    definition:
      'How firm the action is (DATA-08): `estimated` from a pattern, `announced` by the issuer, ' +
      '`confirmed` against a filing, `paid`, or `cancelled`. An estimate is never shown as a fact.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['estimated', 'announced', 'confirmed', 'paid', 'cancelled'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf', 'govt'],
    sources: [src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.status')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'paid', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_DECLARED_DT',
    label: 'Declared date',
    definition: 'Date the issuer announced the action. Blank while the action is only an estimate.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'sec.atom', 'filings', 'entry.updated')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2026-07-30', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_EX_DT',
    label: 'Ex date',
    definition:
      'First session on which the security trades without entitlement to the action. It is the ' +
      'date the price adjustment factors are keyed to (REF-09).',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].events.dividends[].date')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2026-08-10', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_RECORD_DT',
    label: 'Record date',
    definition: 'Date on which a holder must be on the register to receive the action.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [
      src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.record_date'),
    ],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2026-08-11', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_PAY_DT',
    label: 'Pay date',
    definition: 'Date the cash or the new shares actually reach the holder.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.pay_date')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: '2026-08-14', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_EFFECTIVE_DT',
    label: 'Effective date',
    definition:
      'Date a structural action takes effect — the first session under the new ticker, the new ' +
      'name or the post-merger line. Blank for a dividend.',
    type: 'date',
    unit: 'date',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [
      src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.effective_date'),
    ],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'FB US Equity', value: '2022-06-09', asOf: '2026-09-15' },
    since: SINCE,
  },
  {
    id: 'CA_AMOUNT',
    label: 'Action amount',
    definition:
      'Cash per share the action pays, in CA_CRNCY: the dividend rate, the capital return or the ' +
      'tender price. Blank for an action that pays no cash.',
    type: 'number',
    unit: 'ccy',
    decimals: 8,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].events.dividends[].amount')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 0.27, asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_CRNCY',
    label: 'Action currency',
    definition: 'ISO 4217 currency CA_AMOUNT is paid in, which need not be the trading currency.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.currency')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'USD', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_RATIO_NEW',
    label: 'Ratio, new',
    definition:
      'New-share side of a share-count action: 4 for a 4:1 split, 1 for a 1:10 reverse split, 105 ' +
      'for a 5 % stock dividend. Read with CA_RATIO_OLD.',
    type: 'number',
    unit: 'ratio',
    decimals: 6,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].events.splits[].numerator')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 4, asOf: '2020-08-31' },
    since: SINCE,
  },
  {
    id: 'CA_RATIO_OLD',
    label: 'Ratio, old',
    definition:
      'Old-share side of a share-count action: 1 for a 4:1 split, 10 for a 1:10 reverse split, 100 ' +
      'for a 5 % stock dividend. The price factor is CA_RATIO_OLD / CA_RATIO_NEW.',
    type: 'number',
    unit: 'ratio',
    decimals: 6,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'yahoo.chart', 'chart', 'chart.result[0].events.splits[].denominator')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 1, asOf: '2020-08-31' },
    since: SINCE,
  },
  {
    id: 'CA_FREQUENCY',
    label: 'Dividend frequency',
    definition:
      'How often the issuer has been paying this kind of dividend, inferred from the paid history: ' +
      '`quarterly`, `semiannual`, `annual` or `irregular`. It is what an estimated future pay date rests on.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['quarterly', 'semiannual', 'annual', 'irregular'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.frequency')],
    updateFreq: 'quarterly',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'quarterly', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_GROSS_NET',
    label: 'Gross or net',
    definition:
      'Whether CA_AMOUNT is before (`gross`) or after (`net`) withholding tax. Total-return series ' +
      'built from the two are not comparable.',
    type: 'enum',
    unit: 'enum',
    decimals: null,
    enumValues: ['gross', 'net'],
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [
      src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.gross_or_net'),
    ],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'AAPL US Equity', value: 'gross', asOf: '2026-08-08' },
    since: SINCE,
  },
  {
    id: 'CA_NEW_TICKER',
    label: 'New ticker',
    definition:
      'Ticker the security trades under after a ticker change, or the acquirer’s ticker after a ' +
      'merger. Blank for every action that does not change the line.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: ['equity', 'etf'],
    sources: [src('equity', 'internal.derived', 'corporateActions', 'corporate_actions.details')],
    updateFreq: 'daily',
    pit: true,
    example: { ref: 'FB US Equity', value: 'META', asOf: '2022-06-09' },
    since: SINCE,
  },
  // ── Harvested ids kept for coverage ─────────────────────────────────────────────────────────
  // CONTRACTS §4.3 collects every identifier the design writes in field position. Two of the
  // reference-family entries there are not data fields: they are a wildcard and a command token.
  // They are declared (so the dictionary covers the whole list and `GET /fields/:id` answers
  // rather than 404s) and deprecated on the same day, so the generator can drop them once §4.3 is
  // regenerated from this dictionary instead of from prose.
  {
    id: 'OPT_',
    label: 'Option field family',
    definition:
      'Not a field: the OPT_* prefix, harvested from wildcard references to the option field ' +
      'family. Use the concrete member — OPT_STRIKE_PX, OPT_DELTA, OPT_IV and the rest.',
    type: 'string',
    unit: 'text',
    decimals: null,
    fieldClass: 'reference',
    assetClasses: [],
    sources: [],
    updateFreq: 'static',
    pit: false,
    example: { ref: '-', value: 'OPT_*', asOf: '2026-09-17' },
    since: SINCE,
    deprecated: { since: SINCE, replacement: null, removeAfter: REMOVE_AFTER },
  },
  {
    id: 'CPNTO',
    label: 'Coupon upper bound (screener token)',
    definition:
      'Not a field: the SRCH screener keyed token CPNTO=<rate>, which bounds a coupon filter from ' +
      'above. The coupon itself is carried by CPN_FREQ and the govt terms block.',
    type: 'number',
    unit: 'pct',
    decimals: 3,
    fieldClass: 'reference',
    assetClasses: [],
    sources: [],
    updateFreq: 'static',
    pit: false,
    example: { ref: '-', value: 'CPNTO=5', asOf: '2026-09-17' },
    since: SINCE,
    deprecated: { since: SINCE, replacement: null, removeAfter: REMOVE_AFTER },
  },
];
