/**
 * `test/integration/functions/golden.ts` — the one way a Tier-1 payload is compared with its
 * committed golden (`fixtures/golden/functions/<CODE>.<variant>.json`, frozen clock
 * `2026-09-15T18:41:28Z`).
 *
 * Every golden test did the same three lines by hand — read the file, parse it, `toEqual` — and the
 * only thing missing was a way to *write* one. That matters more than the duplication: a golden
 * that cannot be regenerated by running the suite is a golden that gets hand-edited when a
 * resolver legitimately changes, and a hand-edited golden proves self-consistency and nothing
 * about the payload it is supposed to pin.
 *
 * ```
 *   UPDATE_GOLDENS=1 npx vitest run --project server-int test/integration/functions
 * ```
 *
 * rewrites every golden from the resolver's own output and passes. Without the variable — which is
 * how CI and every ordinary run behave — nothing is written and a difference is a failure.
 *
 * A regenerated golden is a **diff to read**, not a result to accept: the run that produced it is
 * the same run the assertion would have failed on, so the question the reviewer answers is whether
 * the change to the payload was intended.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expect } from 'vitest';

/** `fixtures/golden/functions/` with a trailing slash, resolved from this file. */
export const GOLDEN_DIR = fileURLToPath(
  new URL('../../../../../fixtures/golden/functions/', import.meta.url),
);

/** The absolute path of one golden. */
export function goldenPath(name: string): string {
  return `${GOLDEN_DIR}${name}`;
}

/** True when this run is regenerating goldens rather than asserting them. */
export function updatingGoldens(): boolean {
  const flag = process.env.UPDATE_GOLDENS;
  return flag !== undefined && flag !== '' && flag !== '0';
}

/**
 * Assert `actual` against the golden named `name` (`'Q.quote.json'`), or write it when
 * `UPDATE_GOLDENS` is set.
 *
 * `actual` must already be normalised — sequence-allocated ids replaced by tokens — because the
 * file is committed and a `bigserial` value is not reproducible between runs (TESTING §4.3).
 */
export function expectGolden(name: string, actual: unknown): void {
  const path = goldenPath(name);
  if (updatingGoldens()) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${JSON.stringify(actual, null, 2)}\n`, 'utf8');
    return;
  }
  const golden: unknown = JSON.parse(readFileSync(path, 'utf8'));
  expect(actual, name).toEqual(golden);
}
