/**
 * `test/integration/functions/golden.ts` — the one way a Tier-1 payload is compared with its
 * committed golden (`fixtures/golden/functions/<CODE>.<variant>.json`, frozen clock
 * `2026-09-15T18:41:28Z`).
 *
 * Every golden test did the same three lines by hand — read the file, parse it, `toEqual` — and the
 * only thing missing was a way to *write* one. That matters more than the duplication: a golden
 * that cannot be regenerated by running the suite is a golden that gets hand-edited when a
 * resolver legitimately changes, and a hand-edited golden proves self-consistency and nothing
 * about the payload it is supposed to pin.
 *
 * ```
 *   UPDATE_GOLDENS=1 npx vitest run --project server-int test/integration/functions
 * ```
 *
 * rewrites every golden from the resolver's own output and passes. Without the variable — which is
 * how CI and every ordinary run behave — nothing is written and a difference is a failure.
 *
 * A regenerated golden is a **diff to read**, not a result to accept: the run that produced it is
 * the same run the assertion would have failed on, so the question the reviewer answers is whether
 * the change to the payload was intended.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expect } from 'vitest';

/** `fixtures/golden/functions/` with a trailing slash, resolved from this file. */
export const GOLDEN_DIR = fileURLToPath(
  new URL('../../../../../fixtures/golden/functions/', import.meta.url),
);

/** The absolute path of one golden. */
export function goldenPath(name: string): string {
  return `${GOLDEN_DIR}${name}`;
}

/** True when this run is regenerating goldens rather than asserting them. */
export function updatingGoldens(): boolean {
  const flag = process.env.UPDATE_GOLDENS;
  return flag !== undefined && flag !== '' && flag !== '0';
}

/**
 * Replace a sequence-allocated id inside a **subject** string (`q:42`, `l:7`, `b1m:42`,
 * `n:topic:12`, `room:3`) and leave every other string exactly as it was served.
 *
 * A payload carries an id in two places: as a number, which the caller's `JSON.stringify` replacer
 * tokenises directly, and as the tail of a subject. Every one of these tests used to substitute
 * *anywhere in any string* — `value.split(String(id)).join(token)` — which makes the golden a
 * function of the database's sequence state rather than of the payload. Two runs that changed
 * nothing failed on it: a watchlist id of 41 rewrote the frozen `asOf` as
 * `2026-09-15T18:<WATCHLIST>:28.000Z`, and a topic id of 202 rewrote the year as `<TOPIC14>6`. The
 * ids grow with every run, so the failure arrives, leaves and returns on its own.
 *
 * A digit-boundary rule is not enough — `18:41:28` has a colon on each side of the 41 — so the test
 * is the subject *shape* instead: one or more lowercase families, each followed by `:`, then the id
 * and nothing else.
 *
 * A payload that quotes an id somewhere else (MSG's message bodies, `W 41` and `portfolio #7`) needs
 * a normaliser of its own and must not use this one.
 */
export function subjectToken(value: string, tokens: ReadonlyMap<number, string>): string {
  const match = /^((?:[a-z][a-z0-9_]*:)+)(\d+)$/.exec(value);
  if (match === null) return value;
  const token = tokens.get(Number(match[2]));
  return token === undefined ? value : `${match[1] ?? ''}${token}`;
}

/**
 * Replace a sequence-allocated id that sits under a **key which names one** (`instrumentId`,
 * `newsId`, `watchlistId`, or an array of them like `mdLineIds`) and leave every other number
 * exactly as it was served.
 *
 * This is the number-valued twin of `subjectToken`, and it exists for the same reason. Every
 * golden test used to write `if (typeof value === 'number' && tokens.has(value)) -> token`, which
 * rewrites a number because of what it *equals* rather than where it *sits*: any price, quantity,
 * count, weight, basis-point move or epoch field that happens to collide with a live sequence
 * value is silently renamed, and the golden becomes a function of the database's sequence state.
 * It is not hypothetical — the run on which `chat_rooms` reached 330 rewrote MSG's seeded IOI
 * `price: 330` as `<OTHERROOM>` — and the collision space grows with every run, because the
 * instrument sequence climbs by thousands per suite.
 *
 * `idKeys` is therefore the payload's own list of id-bearing keys, per test, read off the payload
 * type rather than guessed. A number under any other key is asserted literally; a number under an
 * id key that is *not* a seeded id (a formula row's `instrumentId: 0`) is left alone too, because
 * the token map is what says which ids this test controls.
 */
export function idToken(
  key: string,
  value: unknown,
  idKeys: ReadonlySet<string>,
  tokens: ReadonlyMap<number, string>,
): unknown {
  if (!idKeys.has(key)) return value;
  if (typeof value === 'number') return tokens.get(value) ?? value;
  if (Array.isArray(value)) {
    const items: readonly unknown[] = value;
    return items.map((item) => (typeof item === 'number' ? (tokens.get(item) ?? item) : item));
  }
  return value;
}

/**
 * Assert `actual` against the golden named `name` (`'Q.quote.json'`), or write it when
 * `UPDATE_GOLDENS` is set.
 *
 * `actual` must already be normalised — sequence-allocated ids replaced by tokens — because the
 * file is committed and a `bigserial` value is not reproducible between runs (TESTING §4.3).
 */
export function expectGolden(name: string, actual: unknown): void {
  const path = goldenPath(name);
  if (updatingGoldens()) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${JSON.stringify(actual, null, 2)}\n`, 'utf8');
    return;
  }
  const golden: unknown = JSON.parse(readFileSync(path, 'utf8'));
  expect(actual, name).toEqual(golden);
}
